### PR TITLE
Build aggregation automatically after other jobs complete

### PR DESCRIPTION
**Pull request by jonahgraham**
@merks I am not sure if this syntax is correct, not sure how to test without merging. I created this because at the moment the https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/index.html is from July 18th, but https://download.eclipse.org/tools/orbit/simrel/maven-bnd/nightly/index.html is from July 21st

### CODE REVIEW

**Comment by jonahgraham** [comment]
I didn't want to conflict with anything you are doing - if you are ok I can merge + test this change myself.

**Comment by merks** [comment]
I think the syntax is supposed to be like this:

https://www.jenkins.io/doc/book/pipeline/syntax/#triggers

There it shows this example:
```
 triggers { upstream(upstreamProjects: 'job1,job2', threshold: hudson.model.Result.SUCCESS)
```
I will experiment with it today...

**Comment by merks** [comment]
I started to wonder now too.  The job with the default parameters does a nightly build with the nightly builds of the dependencies, but the job triggering it might be a milestone or release build.  Oh well, no harm done triggering a nightly build that might not be needed.

I tested that the triggers work:

image

**Comment by jonahgraham** [comment]
Thanks Ed.

**Comment by jonahgraham** [comment]
@merks - the build ran without being promoted:

https://ci.eclipse.org/orbit/job/orbit-simrel-orbit-aggregation/16/parameters/

so https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/index.html doesn't have all contents from maven-bnd + maven-osgi.

**Comment by merks** [comment]
I changed all the builds to promote by default.   

I kicked off this build without promotion so that the parameter definition change is "recorded":

https://ci.eclipse.org/orbit/job/orbit-simrel-orbit-aggregation/17/

Then I kicked off this

https://ci.eclipse.org/orbit/job/orbit-simrel-maven-bnd/21/

which should trigger orbit-simrel-orbit-aggregation again, but with promotion.  I will look a little later to see that it's actually promoted!

**Comment by jonahgraham** [comment]
Thanks Ed - https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/N202307221529/index.html is now present so it looks like it worked :)

**Pull request closed without merging**
